stages:
  - test
  - build
  - deploy

test-backend:
  tags: ["docker"]
  image: amazoncorretto:21-alpine
  stage: test
  script:
    - cd backend
    - mv /cache/$CI_PROJECT_NAME/.gradle . || echo ""
    - ./gradlew test

build-backend:
  tags: ["docker"]
  image: amazoncorretto:21-alpine
  stage: build
  script:
    - cd backend
    - ./gradlew build
    - mv .gradle/ /cache/$CI_PROJECT_NAME/

build-frontend:
  tags: ["docker"]
  image: node:alpine
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build

deploy-backend:
  tags: ["docker"]
  stage: deploy
  image: docker 
  script:
    - echo "Deploying backend..."
    - mv ./backend/build/libs/backend-all.jar $COMMON_SERVICES/sushi-counter/_backend.jar
    - cd $COMMON_SERVICES/sushi-counter
    - docker compose down
    - rm -f backend.jar
    - mv _backend.jar backend.jar
    - ls
    - file backend.jar
    - docker compose up -d

deploy-frontend:
  tags: ["docker"]
  stage: deploy
  script:
    - echo "Deploying frontend..."
    - mv ./frontend/dist/ $COMMON_WWW
    - cd $COMMON_WWW
    - rm -rf sushi-counter/
    - mv dist sushi-counter
